
image:
  file: .gitpod.Dockerfile

tasks:
  - init: composer install --no-interaction
  - before: php artisan key:generate
  - command: php artisan migrate --force || true; php artisan serve --host=0.0.0.0 --port=8000
ports:
  - port: 8000
    onOpen: open-preview
